# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 
# 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

total_sum = 0
last_2_numbers_array = [0,1]

while last_2_numbers_array[1] <= 4e6 do
  sum_of_last_2_numbers = last_2_numbers_array.inject(:+)
  last_2_numbers_array[0] = last_2_numbers_array[1]
  last_2_numbers_array[1] = sum_of_last_2_numbers
  total_sum += sum_of_last_2_numbers if sum_of_last_2_numbers%2 == 0
end

puts total_sum

